from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Profile',
    'Report',
    'Prediction',
    'TriageNote',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Profile': {
        'Reports': 'Report',
        'Predictions': 'Prediction',
        'TriageNotes': 'TriageNote',
    },
    'Report': {
        'Predictions': 'Prediction',
        'Profile': 'Profile',
    },
    'Prediction': {
        'Report': 'Report',
        'Profile': 'Profile',
        'TriageNotes': 'TriageNote',
    },
    'TriageNote': {
        'Prediction': 'Prediction',
        'Profile': 'Profile',
    },
}

# fmt: on